name: flutter_key_value_file_storage
description: An implementation to save big chunks of content to a file
version: 0.0.5
homepage: https://github.com/icapps/flutter_key_value_file_storage

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  device_info_plus: ^8.0.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^6.0.0
  path: ^1.8.1
  path_provider: ^2.0.11
  synchronized: ^3.0.0+3

dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  mockito: ^5.2.0

flutter:
  plugin:
    platforms:
      android:
        package: com.icapps.flutter_key_value_file_storage
        pluginClass: FlutterKeyValueFileStoragePlugin
      ios:
        pluginClass: FlutterKeyValueFileStoragePlugin
